package http

const (
	HeaderUserAgent                   = "User-Agent"
	HeaderXForwardedFor               = "X-Forwarded-For"
	HeaderXAccelBuffering             = "X-Accel-Buffering"
	HeaderAuth                        = "HeaderAuth"
	HeaderContentType                 = "Content-Type"
	HeaderTrace                       = "Tracing"
	HeaderTraceID                     = "Tracing-ID"
	HeaderTraceBin                    = "Tracing-Bin"
	HeaderAuthorization               = "Authorization"
	HeaderCookie                      = "Cookie"
	HeaderCookieValueToken            = "token"
	HeaderCookieValueDel              = "del"
	HeaderContentDisposition          = "Content-Disposition"
	HeaderContentEncoding             = "Content-Encoding"
	HeaderReferer                     = "Referer"
	HeaderAccept                      = "Accept"
	HeaderAcceptCharset               = "Accept-Charset"
	HeaderAcceptLanguage              = "Accept-Language"
	HeaderAcceptEncoding              = "Accept-Encoding"
	HeaderCacheControl                = "Cache-Control"
	HeaderSetCookie                   = "Set-Cookie"
	HeaderTrailer                     = "Trailer"
	HeaderTransferEncoding            = "Transfer-Encoding"
	HeaderTransferEncodingChunked     = "chunked"
	HeaderTE                          = "TE"
	HeaderLastModified                = "Last-Modified"
	HeaderContentLength               = "Content-Length"
	HeaderAccessControlRequestMethod  = "Access-Control-Request-Method"
	HeaderAccessControlRequestHeaders = "Access-Control-Request-Headers"
	HeaderOrigin                      = "Origin"
	HeaderConnection                  = "Connection"
	HeaderRange                       = "Range"
	HeaderHost                        = "Host"
	HeaderVia                         = "Via"
	HeaderDate                        = "Date"
	HeaderExpect                      = "Expect"
	HeaderFrom                        = "From"
	HeaderPragma                      = "Pragma"
	HeaderWarning                     = "Warning"
	HeaderContentRange                = "Content-Range"
	HeaderAcceptRanges                = "Accept-Ranges"
	HeaderXForwardedHost              = "X-Forwarded-Host"
)

const (
	HeaderGrpcTraceBin = "Grpc-Trace-Bin"
	HeaderGrpcInternal = "Grpc-Internal"
	HeaderGrpcStatus   = "Grpc-Status"
	HeaderGrpcMsg      = "Grpc-Msg"
	HeaderGrpcMessage  = "Grpc-Message"
	HeaderErrorCode    = "Error-Code"
)

const (
	HeaderDeviceInfo = "Device-Info"
	HeaderAppInfo    = "App-Info"
	HeaderLocation   = "Location"
	HeaderArea       = "Area"
	HeaderInternal   = "Internal"
)
